services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: djangojwt_app
    command: python manage.py runserver 0.0.0.0:8000
    env_file:
      - .env.dev
    volumes:
      - .:/app
      - ./certs:/app/certs:ro
    ports:
      - "8000:8000"
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy


  postgres:
    image: postgres:16
    container_name: djangojwt_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB:-djangojwt}
      POSTGRES_USER: ${POSTGRES_USER:-djangojwt}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-djangojwt}
    ports:
      - "5432:5432"
    volumes:
      - djangojwt_postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 10


  redis:
    image: redis:7
    container_name: djangojwt_redis
    ports:
      - "6379:6379"
    volumes:
      - djangojwt_redis_data:/data
    command: redis-server --appendonly yes
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10


volumes:
  djangojwt_postgres_data:
  djangojwt_redis_data: