# Generated by Django 6.0.4 on 2026-04-23 19:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contentitem',
            options={'verbose_name': 'Контент', 'verbose_name_plural': 'Контент'},
        ),
        migrations.AlterModelTable(
            name='contentitem',
            table='Content',
        ),
    ]
